@startuml

left to right direction

actor "Miembro" as member
actor "Supervisor" as supervisor
supervisor -u-|> member

rectangle "Sistema Gestión Tareas" {
    usecase "Crear Tarea" as UC1
    usecase "Consultar Tarea" as UC2
    usecase "Aceptar Tarea" as UC3
    usecase "Solicitar Revisión" as UC4
    usecase "Consultar Mis Tareas" as UC5

    usecase "Asignar Tarea" as UC6
    usecase "Aprobar Tarea" as UC7
    usecase "Rechazar Tarea" as UC8
    usecase "Cancelar Tarea" as UC9
    usecase "Consultar Todas\nlas Tareas" as UC10

    usecase "Crear Usuario" as UCU1
    usecase "Activar Usuario" as UCU2
    usecase "Suspender Usuario" as UCU3
    usecase "Reactivar Usuario" as UCU4
    usecase "Desactivar Usuario" as UCU5
}

member --> UC1
member --> UC2
member --> UC3
member --> UC4
member --> UC5

supervisor --> UC6
supervisor --> UC7
supervisor --> UC8
supervisor --> UC9
supervisor --> UC10

supervisor --> UCU1
supervisor --> UCU2
supervisor --> UCU3
supervisor --> UCU4
supervisor --> UCU5

@enduml