@startuml

state "NO_AUTENTICADO" as NoAuth
state "MENU_PRINCIPAL" as Menu
state "EN_TEST" as Test
state "REVISION_TEST" as Revision
state "GESTION_PAQUETES" as Paquetes
state "VISUALIZACION_ESTADISTICAS" as Stats

[*] --> NoAuth

NoAuth --> Menu
    note on link
        Iniciar sesión
    end note

Menu --> NoAuth
    note on link
        Cerrar sesión
    end note

Menu --> Test
    note on link
        Realizar test
    end note

Menu --> Revision
    note on link
        Ver test corregido
    end note

Menu --> Stats
    note on link
        Ver estadísticas
    end note

Menu --> Paquetes
    note on link
        Comprar paquetes
        Resincronizar paquetes
    end note

Test --> Test
    note on link
        Realizar duda
    end note

Revision --> Revision
    note on link
        Realizar duda
    end note

Test --> Menu
    note on link
        Finalizar test
    end note

Revision --> Menu
    note on link
        Volver al menú
    end note

Stats --> Menu
    note on link
        Volver al menú
    end note

Paquetes --> Menu
    note on link
        Finalizar compra/
        Finalizar sincronización
    end note

@enduml