@startuml

title Empty Diagram

class 5Primeros as "Primeros 5 años" {
Escopeta de feria
---
- Lo acaban de inventar/descubrir/publicar
- Alguien lo aplica donde no debe
- Facciones que pelean por la autoria
}


class 5Siguientes as "5 siguientes" {
Reduce significativamente el ruido
---
- Se estudia
- Se contraestudia
- Tesis - Antítesis - Síntesis
}

class 5Posteriores as " 5 siguientes" {
Se asienta
---
- Se conoce dónde es válido
- Se sabe utilizarlo
- Se estandariza
}

5Primeros--r->5Siguientes
5Siguientes--r->5Posteriores

@enduml