@startmindmap

+ La Noticia
++ El mundo que heredan
+++ Llegan
+++ No lo eligieron
++ La responsabilidad en un mundo en movimiento
+++ Ya está funcionando
+++ Tiene sus reglas
+++ No se trata de romperlo
+++ Tiene que seguir,\npara ustedes y sus descendientes
++ Herramientas para gestionar la complejidad
+++ Lo que hemos intentado\nproveerles en la universidad
+++ Análisis de sistemas complejos
+++ Pensamiento crítico
+++ Trabajo en equipo
+++ Ética
+++ Adaptabilidad
++ El momento histórico actual
+++ Desafíos
++++ Tecnología & sociedad
+++ Rol transformador
++++ Evolución y no revolución
++ Cierre
+++ A diferencia del hombre de la noticia,\nuds no se acostarán mientras el mundo arde:\nuds. van a trabajar 

@endmindmap