@startuml modelo-dominio

'skinparam linetype polyline

class ProgresionArmonica

package TeoriaMusical {
    class Nota
    class Calidad
    class Acorde
    class Escala
}

package SistemaArmonico {
    class GradoArmonico
    class FuncionArmonica
    class EnlaceArmonico
    class MapaArmonico
}

' Relaciones de Teoría Musical
Escala *-- Nota : contiene
Acorde o-- Nota : raíz
Acorde o-- Calidad : tiene

' Relaciones del Sistema Armónico
MapaArmonico *- EnlaceArmonico : compone
GradoArmonico o-- Acorde : representa
GradoArmonico o- FuncionArmonica : cumple
EnlaceArmonico o-- Acorde : origen
EnlaceArmonico o-- Acorde : destino
MapaArmonico o-- Escala : en

' Relaciones de Progresión
ProgresionArmonica o-- Acorde : secuencia
ProgresionArmonica ..> MapaArmonico : consulta

@enduml
